# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
cache: cocoapods
podfile: Tests/Podfile
before_install:
- gem install cocoapods -v 1.0.0.beta.8 # Since Travis is not always on latest version
- pod _1.0.0.beta.8_ install --project-directory=Tests
osx_image: xcode7.3
script:
- open -b com.apple.iphonesimulator
- sleep 10
- set -o pipefail && xcodebuild test -workspace Tests/Tests.xcworkspace -scheme Tests-iOS -sdk iphonesimulator | xcpretty
- set -o pipefail && xcodebuild test -workspace Tests/Tests.xcworkspace -scheme Tests-OSX -sdk macosx | xcpretty
